# The project name
project_name = "invoices-service"

# The root package path (e.g., net.wowdev.microservices.products)
package_name = "net.wowdev.ecommerce.invoices"

# The Capitalized noun for the entity (e.g., Product)
domain_object = "Invoice"

# The Kafka publishing topic name (e.g., product-change-topic)
kafka_pub_topic = "invoices-topic.v1"

kafka_bootstrap_servers = "localhost:9092"

# The application server port (e.g., 9000)
app_port = 9500